# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: MrGo-Blog #站点名
subtitle: Web\Linux # 副标题
description: 为了每一次遇见不变的纯真 #站点描述
author: MrGo # 作者，在站点左下角可以看到
language: zh-Hans # 语言。Next主题增加的字段
timezone: Asia/Shanghai
# hexo default is empty, change to exact languages, and add xx.yml under your theme languages dir.
#language: [zh,en]
# config hexo-generator-i18n option (optional, this is default option)
#i18n:
#  type: [page, post]
#  generator: [index, archive, category, tag]
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://mrgo.top
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :lang/:title.md # File name of new posts 建立一个多语种的网站
default_layout: post
titlecase: false  # Transform title into titlecase
external_link: true  # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false  # 链接改为与根目录的相对地址
future: false #显示未来文章
highlight: #hexo自带高亮插件
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

archive_generator:
 per_page: 10 ##归档页面默认20篇文章标题
 yearly: true  ##生成年视图
 monthly: true ##生成月视图

tag_generator:
  per_page: 10 ##标签分类页面默认10篇文章

category_generator:
  per_page: 10 ###分类页面默认10篇文章

search: # 本地搜索插件
  path: search.xml
  field: post
  format: html
  limit: 10000


#页面宠物
# live2d:
#   model: hijiki
  # bottom: -30
  # width: 150 # The width of your model. default: 150
  # height: 300 # The height of your model. default: 300
  # scaling: 1 # The scaling of the resolution. default: 2
  # opacityDefault: 0.7 # The default opacity. default: 0.7
  # opacityHover: 1 # The opacity when hover. default: 1
  # mobileShow:  false  # Whether to show on mobile devices. default: true
  # mobileScaling: 0.5 # The scaling on mobile. default: 0.5
  # position: right # Which side the model is shown at. default: right
  # horizontalOffset: 0 # The horizontal offset. default: 0
  # verticalOffset: -20 # The offset of the bottom. default: -20
  # id: live2dcanvas # The ID of the live2d element. default: live2dcanvas
  # deviceJsSource: local # The source of the current-device script. default: local
  #
live2d:
  enable: true
  scriptFrom: local
  model:
    use: live2d-widget-model-hijiki
    # use: live2d-widget-model-koharu
  display:
    position: right
    width: 80
    height: 160
  react:
      opacityDefault	: 1
  mobile:
    show: false

plugins:
# 自动生成sitemap
sitemap:
path: sitemap.xml
# baidusitemap: # 百度站点地图
# path: baidusitemap.xml

# Deployment 这里的部署很重要
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  # respository:  git@github.com:DAAI093/DAAI093.github.io.git #可选择同时部署到github和coding或者只是部署到guthub,这里只是部署到github
  #  github:  https://github.com/DAAI093/DAAI093.github.io.git
  respository: https://github.com/DAAI093/DAAI093.github.io.git
  branch: master
  message: blog
